@echo off
color 2
del .\Win32\Debug\*.ilc /s
del .\Win32\Debug\*.ild /s
del .\Win32\Debug\*.ilf /s
del .\Win32\Debug\*.ils /s
del .\Win32\Debug\*.map /s
del .\Win32\Debug\*.tds /s
del .\Win32\Debug\*.#00 /s
del .\Win32\Debug\*.#01 /s
del .\Win32\Debug\*.#02 /s
del .\Win32\Debug\*.#03 /s
del .\Win32\Debug\*.obj /s
del .\Win32\Debug\*.pch /s
del .\Win32\Release\*.ilc /s
del .\Win32\Release\*.ild /s
del .\Win32\Release\*.ilf /s
del .\Win32\Release\*.ils /s
del .\Win32\Release\*.map /s
del .\Win32\Release\*.tds /s
del .\Win32\Release\*.#00 /s
del .\Win32\Release\*.#01 /s
del .\Win32\Release\*.#02 /s
del .\Win32\Release\*.#03 /s
del .\Win32\Release\*.obj /s
del .\Win32\Release\*.pch /s
del .\WinServiceApp\Win32\Debug\*.ilc /s
del .\WinServiceApp\Win32\Debug\*.ild /s
del .\WinServiceApp\Win32\Debug\*.ilf /s
del .\WinServiceApp\Win32\Debug\*.ils /s
del .\WinServiceApp\Win32\Debug\*.map /s
del .\WinServiceApp\Win32\Debug\*.tds /s
del .\WinServiceApp\Win32\Debug\*.#00 /s
del .\WinServiceApp\Win32\Debug\*.#01 /s
del .\WinServiceApp\Win32\Debug\*.#02 /s
del .\WinServiceApp\Win32\Debug\*.#03 /s
del .\WinServiceApp\Win32\Debug\*.#04 /s
del .\WinServiceApp\Win32\Debug\*.#05 /s
del .\WinServiceApp\Win32\Debug\*.obj /s
del .\WinServiceApp\Win32\Debug\*.pch /s
del .\WinServiceApp\Win32\Release\*.ilc /s
del .\WinServiceApp\Win32\Release\*.ild /s
del .\WinServiceApp\Win32\Release\*.ilf /s
del .\WinServiceApp\Win32\Release\*.ils /s
del .\WinServiceApp\Win32\Release\*.map /s
del .\WinServiceApp\Win32\Release\*.tds /s
del .\WinServiceApp\Win32\Release\*.#00 /s
del .\WinServiceApp\Win32\Release\*.#01 /s
del .\WinServiceApp\Win32\Release\*.#02 /s
del .\WinServiceApp\Win32\Release\*.#03 /s
del .\WinServiceApp\Win32\Release\*.#04 /s
del .\WinServiceApp\Win32\Release\*.#05 /s
del .\WinServiceApp\Win32\Release\*.obj /s
del .\WinServiceApp\Win32\Release\*.pch /s
pause
